
GRANT USAGE ON SCHEMA hr TO service_role;
GRANT ALL ON ALL TABLES IN SCHEMA hr TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA hr TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr GRANT ALL ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr GRANT ALL ON SEQUENCES TO service_role;
